// This is just some sample data
// The toad quote are from the Super Mario Wiki and is available under a Creative Commons license. Attribution must be provided through a list of authors or a link back to the original article. Source: https://www.mariowiki.com/List_of_Toad_quotes"

const toad = {
  toad1: {
    name: "Red Toad",
    image: "/images/redtoad.png",
    desc: "Thank you! But our princess is in another castle!",
    longitude: 45.489622,
    latitude: -73.845141,
    frontlamp: true,
    backpack: true,
    helmet: true,
    freeUP: true,
    goldMushroom: true,
    invincibilityMushroom: true,
    price: 1200,
    date: 1602196320981
  },
  toad2: {
    name: "Blue Toadette",
    image: "/images/bluetoadette.png",
    desc: "Piece of cake.",
    longitude: 45.529636,
    latitude: -73.624462,
    frontlamp: true,
    backpack: false,
    helmet: true,
    freeUP: true,
    goldMushroom: false,
    invincibilityMushroom: false,
    price: 800,
    date: 1642096320981
  },
  toad3: {
    name: "Yellow Toad",
    image: "/images/yellowtoad.png",
    desc: "I found this cap in front of the castle a little while ago. You look really good in it, so here you go!",
    longitude: 45.441640,
    latitude: -73.620347,
    frontlamp: false,
    backpack: true,
    helmet: true,
    freeUP: false,
    goldMushroom: true,
    invincibilityMushroom: false,
    price: 800,
    date: 1642106320981
  },
  toad4: {
    name: "Green Toad",
    image: "/images/greentoad.png",
    desc: "The mountain in that picture looks like a great place to relax. I bet it's a peaceful land, with no strife.",
    longitude: 45.586184,
    latitude: -73.564791,
    frontlamp: true,
    backpack: true,
    helmet: true,
    freeUP: false,
    goldMushroom: false,
    invincibilityMushroom: false,
    price: 500,
    date: 1602196320981
  },
  toad5: {
    name: "Orange Toadette",
    image: "/images/orangetoadette.png",
    desc: "Sometimes when I'm staring at the fish, I think I wouldn't mind staying here forever. It helps me forget about my horrible fate.",
    longitude: 45.600942,
    latitude: -73.623947,
    frontlamp: true,
    backpack: false,
    helmet: true,
    freeUP: false,
    goldMushroom: false,
    invincibilityMushroom: false,
    price: 600,
    date: 1642190320901
  },
  toad6: {
    name: "Green Toadette",
    image: "/images/greentoadette.png",
    desc: "Wow! You've recovered that many Stars? Way to go! You'll have us out of here in no time!",
    longitude: 45.539005,
    latitude: -73.659956,
    frontlamp: true,
    backpack: false,
    helmet: true,
    freeUP: true,
    goldMushroom: false,
    invincibilityMushroom: true,
    price: 750,
    date: 1640196300981
  },
  toad7: {
    name: "Blue Toad",
    image: "/images/bluetoad.png",
    desc: "I'm your biggest fan! You're the best supporting actor the world's ever seen!",
    longitude: 45.511976,
    latitude: -73.629091,
    frontlamp: false,
    backpack: true,
    helmet: true,
    freeUP: false,
    goldMushroom: true,
    invincibilityMushroom: true,
    price: 650,
    date: 1640106320981
  },
  toad8: {
    name: "Purple Toadette",
    image: "/images/purpletoadette.png",
    desc: "The Power Stars are returning one by one. I feel terrible that I misjudged you.",
    longitude: 45.442357,
    latitude: -73.707505,
    frontlamp: true,
    backpack: false,
    helmet: true,
    freeUP: false,
    goldMushroom: true,
    invincibilityMushroom: false,
    price: 900,
    date: 1642000320981
  },
  toad9: {
    name: "Brown Toadette",
    image: "/images/browntoadette.png",
    desc: "And this brigade needs a bold leader so I nominate...um...well..me! Under my command, the galaxies will see the bravery of the Toad Brigade!",
    longitude: 45.661113,
    latitude: -73.497949,
    frontlamp: true,
    backpack: true,
    helmet: false,
    freeUP: true,
    goldMushroom: true,
    invincibilityMushroom: true,
    price: 950,
    date: 1542096020981
  },
  toad10: {
    name: "Purple Toad",
    image: "/images/purpletoad.png",
    desc: "Ah, Captain, it's terrible! Princess Peach has been taken to another castle!",
    longitude: 45.604031,
    latitude: -73.578874,
    frontlamp: true,
    backpack: true,
    helmet: true,
    freeUP: true,
    goldMushroom: true,
    invincibilityMushroom: false,
    price: 1000,
    date: 1542190320081
  },
};

export default fishes;